### ISSUE TITLE
Request for example of Next.js 13 with App Router

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-component-testing-apps#17]
This is a feature request to extend the examples to cover Next.js 13 with App Router instead of using `pages/`.

Executing `npx create-next-app@latest` with `create-next-app@13.4.3`

defaults to

`√ Use App Router (recommended)? ... No / Yes`

See also announcement [Next.js 13.4](https://nextjs.org/blog/next-13-4) May 4, 2023.

**Comment by stanislavlyu** [comment]
Same problem

**Comment by MikeMcC399** [comment]
This request is outdated, since the latest version of Next.js is now [v14.0.1](https://github.com/vercel/next.js/releases/tag/v14.0.1).

**Comment by manavm1990** [comment]
It's still App Router though - just stable *server actions,* among a few other things.

**Comment by MikeMcC399** [comment]
Cypress is not yet fully compatible with Next.js `14`, see

- https://github.com/cypress-io/cypress/issues/28185
- https://github.com/cypress-io/cypress/issues/27731#issuecomment-1715685684

If/when compatibility with Next.js `14` is declared, then I would close this issue and resubmit as a request for a new example for  Next.js `14` using defaults.

**Comment by MikeMcC399** [comment]
@manavm1990 

> So, Cypress is not going to be 💯 compatible with NextJS 14? :(

I closed this issue about an example because Next.js 13 is no longer the latest version, so the focus should be on Next.js 14 and 15 RC.

The closure of this issue says nothing about the compatibility of Cypress with Next.js 14. If you have a problem using Cypress with Next.js 14, then I suggest you check the issues https://github.com/cypress-io/cypress/issues.
